### ISSUE TITLE
Error in editing or add records

### ISSUE THREAD

**Issue by j209** [Saeed-Hassanpour/APEXPersianDatepicker#2]
![untitled](https://user-images.githubusercontent.com/18129232/44624765-1f9ec280-a90c-11e8-8fbb-92a98a93ba82.png)

**Comment by Saeed-Hassanpour** [comment]
I'm sorry, I forgot to add this setting on current application. 

> Application Date Format [YYYY/MM/DD]

![screenshot 6](https://user-images.githubusercontent.com/17166929/44625188-87f3a100-a918-11e8-9a2a-8764a29e07f7.png)
